# Generated by Django 3.0.3 on 2020-07-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_questions_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='profilePic',
            field=models.ImageField(default='media/user.png', upload_to='media'),
        ),
    ]
