# Generated by Django 3.0.3 on 2020-07-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_questions_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='votes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
